###**Exercício - Módulo 3 - Part II**

####Função Numpy

In [ ]:
import numpy as np

O código acima importa a biblioteca NumPy, permitindo que se utilize as funções e métodos fornecidos por essa biblioteca em seus programas. O "np" é um apelido - alias - que foi dado à biblioteca, substituindo a palavra "numpy" no código, tornando o código mais conciso e legível.

#### 1) Alturas  
i. No trecho de código abaixo, crie um ndarray chamado ```altura_em_centimetros``` transformando a lista ```lista_de_alturas``` em um ndarray do numpy com a função ```np.array()```  

ii. Crie um outro objeto ```altura_em_metros```, com os valores de ```altura_em_centimetros``` convertidos para metros.

In [ ]:
lista_de_alturas = list(range(170, 190, 5))
lista_de_alturas

[170, 175, 180, 185]

In [ ]:
#código abaixo (I):

altura_em_centimetros = np.array(lista_de_alturas)

print(altura_em_centimetros)

[170 175 180 185]


In [ ]:
#código abaixo (II):

altura_em_metros = altura_em_centimetros / 100

print(altura_em_metros)

[1.7  1.75 1.8  1.85]


#### 2) IMC  
i. Considere que pesos em Kg dessas pessoas, na mesma ortem, estão na lista pesos ```lista_pesos = [70, 75, 80, 85]```. Crie um **ndarray** chamado ```pesos``` com a função ```np.array()``` que contenha esses valores.  
ii. Utilizando o objeto que contém as alturas em metros e esse objeto que contém os respectivos pesos em quilos, calcule o IMC desses indivíduos utilizando a aritmética de arrays e guarde os resultados em um objeto chamado ```imc```.

In [ ]:
lista_pesos = [70, 75, 80, 85]
lista_pesos

#código abaixo (I):

pesos = np.array(lista_pesos)

In [ ]:
#código abaixo (II):

imc = pesos / (altura_em_metros**2)
imc = np.round(imc, 2)
print(imc)


[24.22 24.49 24.69 24.84]


#### 3) Endividamento

Cálculos de novas variáveis como endividamento total e comprometimento de renda são essenciais para a construção de modelos financeiros em ciência de dados. Áreas não financeiras terão cálculos semelhantes também. Vamos praticar:

Considere que o seguinte ndarray contém os dados de 4 pessoas, total a ser pago a empréstimos mensalmente e renda familiar:

| custo fixo | dívida financeira | renda familiar |
|:----:|:----:|:---|
| 3000  | 1000 | 6000 |
| 2500  | 2500 | 5500 |
| 1000  | 3000 | 7000 |
| 10000 | 5000 | 16000 |

i. Transforme a lista de listas ```dados_financeiros``` no ndarray ```nd_financeiros```.
> ``` dados_financeiros[[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]] ```

ii. Utilize o método ```.transpose ``` e certifique-se de que esse ndarray tenha uma linha por indivíduo e uma coluna por informação. Utilizando a indexação do numpy, imprima no output a segunda linha do array, depois a segunda coluna.

iii. Pratique aritmética com nearrays e calcule o endividamento total como:
$$endividamento\hspace{.2cm}total = \frac{custo \hspace{.2cm}fixo + dívida\hspace{.2cm}financeira}{renda\hspace{.2cm}familiar}$$
Guarde os resultados em uma variável chamada ```endividamento_total``` e verifique os resultados imprimindo o conteúdo dessa variável no output.

iv. Considere que há um erro de digitação que precisa ser corrigido: 3o indivíduo na verdade não possui renda familiar de R\\$7.000,00, mas sim R\\$ 10.000,00. Corrija esse valor e refaça os cálculos.

In [43]:
# lista dados_financeiros
dados_financeiros = [[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]]
dados_financeiros

#I) transforme essa lista em um ndarray

nd_financeiros = np.array(dados_financeiros)

In [44]:
#II) utilização do método transpose
nd_financeiros_transpose = nd_financeiros.transpose()
print(nd_financeiros_transpose[0])
print(nd_financeiros_transpose[:,1])

[3000 1000 6000]
[1000 2500 3000 5000]


In [45]:
#III) Calcule o endividamento total
soma_custo_divida = nd_financeiros_transpose[:,0].sum() + nd_financeiros_transpose[:,1].sum()
soma_renda = nd_financeiros_transpose[:,2].sum()
endividamento = (soma_custo_divida / soma_renda)

print("O endividamento total em porcentagem é de: {:.2f}%".format(endividamento))

O endividamento total em porcentagem é de: 0.81%


In [47]:
#IV) corrigindo um valor específico (de 7000 para 10000)

dados_financeiros[2][2] = 10000
print(dados_financeiros)

[[3000, 2500, 1000, 10000], [1000, 2500, 3000, 5000], [6000, 5500, 10000, 16000]]


In [48]:
# novo cálculo

nd_financeiros = np.array(dados_financeiros)
nd_financeiros_transpose = nd_financeiros.transpose()
soma_custo_divida = nd_financeiros_transpose[:,0].sum() + nd_financeiros_transpose[:,1].sum()
soma_renda = nd_financeiros_transpose[:,2].sum()
endividamento = (soma_custo_divida / soma_renda)

print("O endividamento total em porcentagem é de: {:.2f}%".format(endividamento))

O endividamento total em porcentagem é de: 0.75%


#### 4) É muito comum precisarmos identificar valores especiais e darmos tratamento a eles quer seja alterando-os quer seja descartando-os. 

O trecho de código abaixo gera um ndarray com números pseudo aleatórios. Considere que para efeitos do estudo que virá, devemos desconsiderar valores iguais a zero. Sendo assim:

i) crie um objeto ```bool_zero``` que traga uma sequencia de booleanos do mesmo tamanho que o objeto poi, e que vale ```True``` quando o valor de ```poi``` é zero, e ```False``` caso contrário.

ii) Conte quantos valores zero existem. Lembre-se de que no final das contas, ```True``` vale 1 para o Python, e ```False``` vale zero, então uma boa dica seria usar a função ```sum()```.

iii) Utilize a indexação booleana que você aprendeu para criar uma variável ```poi_nao_zero``` que aponta para os elementos de ```poi``` diferentes de zero. Dica: você vai pode inverter os elementos do objeto que criou em *ii)* ou escrever a comparação adequada.

In [52]:
# objeto poi - obs: o comando np.random.seed(1234) garante que o mesmo resultado será gerado sempre
np.random.seed(1234)
poi = np.random.poisson(3, 100)
poi

array([3, 3, 6, 2, 4, 5, 4, 4, 2, 0, 3, 3, 2, 8, 2, 3, 3, 3, 0, 4, 4, 2,
       6, 6, 0, 3, 4, 3, 5, 2, 1, 3, 2, 2, 3, 2, 4, 4, 5, 7, 3, 5, 3, 3,
       2, 2, 3, 6, 2, 2, 4, 3, 5, 2, 5, 3, 0, 2, 1, 1, 4, 4, 4, 6, 2, 4,
       1, 2, 5, 5, 3, 4, 1, 4, 1, 1, 7, 1, 2, 1, 3, 7, 0, 4, 4, 0, 6, 1,
       3, 4, 2, 5, 4, 5, 5, 3, 4, 6, 8, 2])

In [54]:
# i) crie o objeto bool_zero através do operador ==

bool_zero = (poi == 0)
print(bool_zero)

[False False False False False False False False False  True False False
 False False False False False False  True False False False False False
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False  True False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False  True False False False False False False False False False False
 False False False False]


In [56]:
#para melhor visualização vou colocar o True em negrito utilizando HTML

from IPython.display import HTML

bool_zero_formatted = ["<b>True</b>" if x else "False" for x in bool_zero]

bool_zero_html = "[" + ", ".join(bool_zero_formatted) + "]"

display(HTML(bool_zero_html))

In [ ]:
# ii) Conte a quantidade de zeros (ou some os elementos de bool_zero)

In [62]:
num_zeros = sum(bool_zero)
print(num_zeros)

6


In [ ]:
# iii) utilize a indexação booleana para criar uma seleção de não-zeros
# dica: inverta o objeto bool_zero

In [63]:
non_zeros = poi[~bool_zero]
print(non_zeros)

[3 3 6 2 4 5 4 4 2 3 3 2 8 2 3 3 3 4 4 2 6 6 3 4 3 5 2 1 3 2 2 3 2 4 4 5 7
 3 5 3 3 2 2 3 6 2 2 4 3 5 2 5 3 2 1 1 4 4 4 6 2 4 1 2 5 5 3 4 1 4 1 1 7 1
 2 1 3 7 4 4 6 1 3 4 2 5 4 5 5 3 4 6 8 2]


In [64]:
num_not_zeros = sum(~bool_zero)
print(num_not_zeros)

94
